// Code generated by prompty-gen. DO NOT EDIT.

package contractgen

import (
	"github.com/go-playground/validator/v10"
	"github.com/skosovsky/prompty"
)

type PromptID string

var validate = validator.New()

type Prompts struct {
	registry prompty.Registry
}

func NewPrompts(r prompty.Registry) *Prompts {
	return &Prompts{registry: r}
}

func AllPromptIDs() []PromptID {
	return []PromptID{AnalyzeCore}
}
