// Code generated by prompty-gen. DO NOT EDIT.

package contractgen

import (
	"context"
	"fmt"
	"github.com/skosovsky/prompty"
)

const AnalyzeCore PromptID = "analyze/core"

type AnalyzeCoreInputUsersItem struct {
	Messages []string `json:"messages" prompt:"messages" validate:"required,dive"`
	User     string   `json:"user" prompt:"user" validate:"required"`
}

type AnalyzeCoreInput struct {
	ChannelUsername string                      `json:"channel_username" prompt:"channel_username" validate:"required"`
	PromptTemplate  string                      `json:"prompt_template" prompt:"prompt_template" validate:"required"`
	Users           []AnalyzeCoreInputUsersItem `json:"users" prompt:"users" validate:"required,dive"`
	UsersJson       string                      `json:"users_json" prompt:"users_json" validate:"required"`
}

type AnalyzeCoreOutputAgitatorsItem struct {
	MessageCount int64  `json:"message_count" prompt:"message_count" validate:"required,gte=0"`
	Style        string `json:"style" prompt:"style" validate:"required"`
	User         string `json:"user" prompt:"user" validate:"required"`
	WhatTriggers string `json:"what_triggers" prompt:"what_triggers" validate:"required"`
	WontPassBy   string `json:"wont_pass_by" prompt:"wont_pass_by" validate:"required"`
}

type AnalyzeCoreOutput struct {
	Agitators []AnalyzeCoreOutputAgitatorsItem `json:"agitators" prompt:"agitators" validate:"required,dive"`
	HotTopics []string                         `json:"hot_topics" prompt:"hot_topics" validate:"required,dive"`
	Notes     *string                          `json:"notes,omitempty" prompt:"notes"`
}

func (p *Prompts) RenderAnalyzeCore(ctx context.Context, input AnalyzeCoreInput) (*prompty.PromptExecution, error) {
	if err := validate.Struct(&input); err != nil {
		return nil, fmt.Errorf("validate input: %w", err)
	}
	tmpl, err := p.registry.GetTemplate(ctx, string(AnalyzeCore))
	if err != nil {
		return nil, fmt.Errorf("get template: %w", err)
	}
	vars := make(map[string]any, 4)
	vars["channel_username"] = input.ChannelUsername
	vars["prompt_template"] = input.PromptTemplate
	vars["users"] = input.Users
	vars["users_json"] = input.UsersJson
	exec, err := tmpl.Format(vars)
	if err != nil {
		return nil, fmt.Errorf("format template: %w", err)
	}
	return exec, nil
}
